### ISSUE TITLE
ability to set different profiles

### ISSUE THREAD

**Issue by strantalis** [opentdf/otdfctl#150]
I would like the ability to set different profiles that allow me to point to different deployed platforms.

Example 

```toml
[platform1]
endpoint = https://platform1.opentdf.io
insecure = true

[platform2]
endpiont = http://platform2.opentdf.io
clientID = opentdf
clientSecret = secret
```
